dist: focal
language: python

python:
  - "3.11"  

# Install dependencies by navigating into the directory where requirements.txt is located
install:
  - cd mysite  # Change directory to where manage.py and requirements.txt are
  - pip install -r requirements.txt  # Install dependencies from requirements.txt
  - pip install black flake8 coverage coveralls 

# Run the code checks and tests with coverage from within the mysite directory
script:
  - black --check .
  - flake8
  - coverage run --source='.' manage.py test  # Run tests with coverage

# After successful tests, send coverage data to Coveralls
after_script:
  - coveralls  # Upload the coverage data to Coveralls

# Optional: Deploy configuration if using Elastic Beanstalk
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEYdjango
  secret_access_key: $AWS_SECRET_KEYdjango
  region: "us-west-2"
  app: "django-tutorial"
  env: "Django-tutorial-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-842226700716"
  on:
    branch: main


