dist: focal
language: python
script: echo "Travis is cool!" 
install: skip
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA4IGE7SGWJ2RV23OX
    secure: "Encrypted <access-key-id>="
  secret_access_key: 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
    secure: "Encypted <secret-access-key>="
  region: "us-west-2"
  app: "Django-App"
  env: "Django-tutorial-env-1"
  bucket_name: "the-target-S3-bucket"
   on:
    branch: main
