dist: focal
language: python

# Install the necessary dependencies
install:
  - pip install black

# Script to run the black check
script:
  - black --check .
  - echo "Travis is cool!"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEYdjango
  secret_access_key: $AWS_SECRET_KEYdjango
  region: "us-west-2"
  app: "django-tutorial"
  env: "Django-tutorial-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-842226700716"
  on:
    branch: main
